// Package apisurface records the exported surface of the packages that carry
// contractual API, so that a change to it shows up as a diff in a checked-in
// file rather than as a surprise for someone downstream.
//
// It reads the source rather than the compiled package, so it needs no build
// step and no dependency. Unexported struct fields are omitted deliberately:
// they are not API, and including them would make every internal change look
// like an API change, which is the fastest way to teach a reviewer to ignore
// the file.
package apisurface

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Packages are the module-relative directories whose surface is recorded.
//
// raft is included even though only its persistence boundary is contractual;
// docs/API.md says which identifiers those are. Recording the whole package
// means a change to the rest still appears in review rather than silently.
var Packages = []string{
	"dst",
	"dst/scenario",
	"raft",
	"storage",
	"storage/storagetest",
	"storage/wal",
}

// Collect renders the exported surface of every recorded package, rooted at
// the module directory. The output is deterministic: packages in the order
// above, declarations sorted within each.
func Collect(root string) (string, error) {
	var out strings.Builder
	out.WriteString("# Exported surface of the packages carrying contractual API.\n")
	out.WriteString("# Generated by internal/apisurface. See docs/API.md.\n")
	for _, pkg := range Packages {
		lines, err := collectPackage(filepath.Join(root, filepath.FromSlash(pkg)))
		if err != nil {
			return "", fmt.Errorf("%s: %w", pkg, err)
		}
		fmt.Fprintf(&out, "\n## %s\n", pkg)
		for _, line := range lines {
			out.WriteString(line)
			out.WriteString("\n")
		}
	}
	return out.String(), nil
}

// block is one declaration and its members. Sorting whole blocks rather than
// individual lines is what keeps a type's fields attached to the type; sorting
// flat lines silently separates them, because an indented member sorts before
// every header.
type block struct {
	key   string
	lines []string
}

func collectPackage(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	fset := token.NewFileSet()
	var blocks []block
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		file, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.SkipObjectResolution)
		if err != nil {
			return nil, err
		}
		blocks = append(blocks, declarations(fset, file)...)
	}
	sort.Slice(blocks, func(i, j int) bool { return blocks[i].key < blocks[j].key })

	var lines []string
	for _, b := range blocks {
		lines = append(lines, b.lines...)
	}
	return lines, nil
}

func declarations(fset *token.FileSet, file *ast.File) []block {
	var blocks []block
	for _, decl := range file.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			if line, ok := function(fset, d); ok {
				blocks = append(blocks, block{key: line, lines: []string{line}})
			}
		case *ast.GenDecl:
			blocks = append(blocks, generic(fset, d)...)
		}
	}
	return blocks
}

func function(fset *token.FileSet, d *ast.FuncDecl) (string, bool) {
	if !d.Name.IsExported() {
		return "", false
	}
	if d.Recv != nil && len(d.Recv.List) > 0 {
		// A method on an unexported type is not reachable from outside.
		if !exportedReceiver(d.Recv.List[0].Type) {
			return "", false
		}
	}
	signature := *d
	signature.Body = nil
	signature.Doc = nil
	return "func " + strings.TrimPrefix(render(fset, &signature), "func "), true
}

func exportedReceiver(expr ast.Expr) bool {
	switch t := expr.(type) {
	case *ast.StarExpr:
		return exportedReceiver(t.X)
	case *ast.Ident:
		return t.IsExported()
	case *ast.IndexExpr: // generic receiver, for example Engine[M]
		return exportedReceiver(t.X)
	case *ast.IndexListExpr:
		return exportedReceiver(t.X)
	}
	return false
}

func generic(fset *token.FileSet, d *ast.GenDecl) []block {
	var blocks []block
	for _, spec := range d.Specs {
		switch s := spec.(type) {
		case *ast.ValueSpec:
			for _, name := range s.Names {
				if name.IsExported() {
					line := fmt.Sprintf("%s %s", d.Tok, name.Name)
					blocks = append(blocks, block{key: line, lines: []string{line}})
				}
			}
		case *ast.TypeSpec:
			if s.Name.IsExported() {
				lines := typeSpec(fset, s)
				blocks = append(blocks, block{key: lines[0], lines: lines})
			}
		}
	}
	return blocks
}

// typeParams renders a generic parameter list. go/printer cannot print a bare
// ast.FieldList, so it is assembled by hand.
func typeParams(fset *token.FileSet, list *ast.FieldList) string {
	if list == nil || len(list.List) == 0 {
		return ""
	}
	var groups []string
	for _, field := range list.List {
		var names []string
		for _, name := range field.Names {
			names = append(names, name.Name)
		}
		groups = append(groups, strings.Join(names, ", ")+" "+render(fset, field.Type))
	}
	return "[" + strings.Join(groups, ", ") + "]"
}

func typeSpec(fset *token.FileSet, s *ast.TypeSpec) []string {
	name := s.Name.Name + typeParams(fset, s.TypeParams)
	switch t := s.Type.(type) {
	case *ast.StructType:
		lines := []string{"type " + name + " struct"}
		for _, field := range t.Fields.List {
			for _, fieldName := range field.Names {
				if fieldName.IsExported() {
					lines = append(lines, fmt.Sprintf("    %s.%s %s", s.Name.Name, fieldName.Name, render(fset, field.Type)))
				}
			}
		}
		return lines
	case *ast.InterfaceType:
		lines := []string{"type " + name + " interface"}
		for _, method := range t.Methods.List {
			for _, methodName := range method.Names {
				lines = append(lines, fmt.Sprintf("    %s.%s%s", s.Name.Name, methodName.Name,
					strings.TrimPrefix(render(fset, method.Type), "func")))
			}
		}
		return lines
	default:
		return []string{"type " + name + " " + render(fset, s.Type)}
	}
}

func render(fset *token.FileSet, node ast.Node) string {
	var out strings.Builder
	if err := (&printer.Config{Mode: printer.RawFormat}).Fprint(&out, fset, node); err != nil {
		return "<unprintable>"
	}
	return strings.Join(strings.Fields(out.String()), " ")
}
